version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: Clone docs
          working_directory: ~/workdir
          command: |
            git clone --depth 1 https://$1ba566f4f5b37b42efdb238c8ebb46573b89a25d@https://github.com/strategyfoundry/wimm-portal-server.git
      - deploy:
          name: Trigger docs deployment
          working_directory: ~/workdir/docs
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "<email>"
            git config user.name "Deployment Bot"
            git commit --allow-empty -m "Trigger deployment"
            # Push quietly to prevent showing the token in log
            git push -q https://$1ba566f4f5b37b42efdb238c8ebb46573b89a25d@https://github.com/strategyfoundry/wimm-portal-server.git
